### ISSUE TITLE
context.services.users.getOAuthUser is missing (so far)

### ISSUE THREAD

**Issue by Scarygami** [dart-lang/appengine#10]
I saw that the call is prepared in the [protobuf services](https://github.com/dart-lang/appengine/blob/master/lib/src/protobuf_api/user_service.dart#L48) but it isn't yet exposed in context.services.users

This method would be very useful for checking who made an authenticated call to the server (without having to check the Authorization header manually).

**Comment by mkustermann** [comment]
With the recent version of `package:appengine` the users service has been removed - the necessary APIs are no longer available within the new AppEngine flexible environment.
