### ISSUE TITLE
provide adapter for core logging library onto appengine logging

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/appengine#11]
AFAICT the core logging package is very widely used in Dart. It makes sense to provide an adapter for that onto the appengine logging package. 

I've knocked something up for my own use that I've included below. It turned out to be quite a lot fiddlier than I expected due to that the appengine logger is accessed via a Zone variable.

## The adapter itself ##

```
library logging.appengine.adapter;
import 'package:logging/logging.dart';
import 'package:appengine/appengine.dart';
import 'package:stack_trace/stack_trace.dart';

typedef LogRecordProcessor(LogRecord logRecord);


sendToAELogger(LogRecord logRecord) {
  final Logging aeLogging = context.services.logging;
  aeLogging.log(_aeLogLevel(logRecord.level), _createMessage(logRecord));
}

String _createMessage(LogRecord logRecord) {
  final msg = '${logRecord.loggerName}: ${logRecord.message}';
  return logRecord.error != null ?
      '$msg: ${_createErrorMessage(logRecord.error, logRecord.stackTrace)}'
      : msg;
}


final Map<Level, LogLevel> _levelMap = {
  Level.FINEST: LogLevel.DEBUG,
  Level.FINER: LogLevel.DEBUG,
  Level.FINE: LogLevel.DEBUG,
  Level.INFO: LogLevel.INFO,
  Level.CONFIG: LogLevel.INFO,
  Level.WARNING: LogLevel.WARNING,
  Level.SEVERE: LogLevel.ERROR,
  Level.SHOUT: LogLevel.CRITICAL
};

LogLevel _aeLogLevel(Level level) => _levelMap[level];

String _createErrorMessage(Object error, StackTrace stack) {

  var chain = new Chain.current();
  if (stack != null) {
    chain = new Chain.forTrace(stack)
      .foldFrames((frame) => true)
      .terse;
  }

  var msg = '$error';
  if(chain == null) return msg;

  return '$msg\n$chain';
}

```

## The shelf middleware ##

The shelf middleware was needed to get around the Zone variable issue. Not pretty but seems to work

```
  Handler _adaptLogging(Handler innerHandler) {
    return (request) {
      var streamSubscription = Logger.root.onRecord.listen(sendToAELogger);
      return new Future.sync(() => innerHandler(request)).whenComplete(() {
        streamSubscription.cancel();
      });
    };
  }

```

**Comment by Andersmholmgren** [comment]
Fantastic. I hope you find a way to integrate into appengine but at least I can now use the logging package and have at all work. Thanks a lot for this

**Comment by mkustermann** [comment]
This has landed in d86fb8ee85536343eb010b40039fab30e7f0e6be and will be useable with `useLoggingPackageAdaptor()`.

**Comment by Andersmholmgren** [comment]
\o/ great news. Thanks

**Comment by mkustermann** [comment]
The next `0.2.6` release was made & published on pub. It includes another change to work around an issue with an incorrect `requestedUri` comming from `dart:io`.

**Comment by zoechi** [comment]
Where does the log output go during local development?

**Comment by mkustermann** [comment]
For local development, the log entries are written to stdout/stderr (the same information as we also send to the stackdriver logging service, grouped by requests).

If you are running it without docker, you should see it in the output of the console.

Of course, this only applies if `useAppEngineLoggingAdaptor()` was called, which will then listen for `package:logging` messages.

**Comment by zoechi** [comment]
@mkustermann I didn't investigate further yet, it seems some early log entries are not printed, but I have seen actual log output on the console already.
I was stuck with other issues. I'll post another comment here when I know more.
