### ISSUE TITLE
New `grpc: 3.1.0` breaks Flutter `cocoon` repo CI

### ISSUE THREAD

**Issue by keyonghan** [dart-lang/appengine#154]
A new version of `grpc: 3.1.0` was released 35 hours ago, which implemented `onConnectionStateChanged` in https://github.com/grpc/grpc-dart/pull/565/files. However this change doesn't seem handled from appengine side, and it caused breakage from Flutter Cocoon repo CI:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8799111100632269761/+/u/auto_submit/stdout

The new element should be addressed in https://github.com/dart-lang/appengine/blob/master/lib/src/appengine_internal.dart#L292

**Comment by devoncarew** [comment]
Thanks for the heads up! We weren't aware of the dep on here from coccoon.

Would you be up for sending a PR? This package is in our labs publisher (labs.dart.dev), so has no real SLO.
