### ISSUE TITLE
populate ETAG and LAST-MODIFIED for assests

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/appengine#17]
I can't get caching to work for my assets serviced from the appengine context. Unless there is some magic that is intended to occur in Googles CDN then I imagine the reason is that appengine / shelf_appengine do not populate ETAG and LAST-MODIFIED  on the assets

**Comment by sigurdm** [comment]
shelf_appengine has been discontinued.
Closing as assumed stale.
