### ISSUE TITLE
Documentation on model?

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/appengine#28]
It's pretty difficult to find out what can go in the property annotations of the model. This may be a problem with the gcloud lib rather than this one.

I presume the supported types are pretty much these: https://cloud.google.com/appengine/docs/python/datastore/typesandpropertyclasses

But it would be nice to know in an easier to find way.

**Comment by lukechurch** [comment]
Hmm, actually they don't seem to match the Python model, they seem to be more Darty, which is nice. But still, difficult to discover.

**Comment by sigurdm** [comment]
Assuming stale
