### ISSUE TITLE
Cannot call module from Dart module

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/appengine#32]
Report from developer:

In local development (localhost), I'm trying to make http post request from dart module to another module by using package:http library.

I expected it should work just like Python appengine's way (using module service to get the target module, then urlfetch with the url). So I used "context.services.modules.hostname('module name')" to get the target module's hostname and make a http request to the host. But I got errors like,

DEBUG    2015-02-27 07:25:49,186 containers.py:645] Container: 83bf4b014a36: 2015-02-27 07:25:49.653: ApplicationLog | Error: Uncaught error in request handler: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 42430
null
DEBUG    2015-02-27 07:25:49,188 containers.py:645] Container: 83bf4b014a36: Uncaught error in request handler zone: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 42430
Stack:

(I set --verbosity debug)

Also I tried to specify the dispatcher's hostname (my case was localhost:8080 which was default setting) explicitly to expect it routed to the target module, but it routed to the request sender and made no scense. Judging from the CONTAINER ID, It looked like the request was processed inside the container, not the dispatcher.
I also saw same problem on locally editing appengine_samples/modules (https://github.com/dart-lang/appengine_samples/tree/master/modules). In the case I added a http requst from "module: default" to "module: module-dart".

What am I missing? Best way to call module from Dart managed VM module? Maybe I need to set some port forwarding thing around Docker?

**Comment by sgjesse** [comment]
You are right that the URLs returned by "context.services.modules.hostname('module name')"  does not work for local development. They are just localhost:XXXX which are the URLs you can use from the host to get to each docker container running the individual modules.

However the boot2docker configuration uses the address 10.0.2.2 to get back to the host. This is the address the modules uses to call the App Engine APIs exposed (which are running on the host). If you replace localhost with 10.0.2.2 you should be able to talk to another module.

If you take the modules sample in https://github.com/dart-lang/appengine_samples, and change the _requestHandler in the Dart module (in https://github.com/dart-lang/appengine_samples/tree/master/modules/module-dart/bin) like this:

void _requestHandler(HttpRequest request) {
  request.drain().then((_) {
    var client = new HttpClient();
    context.services.modules.hostname('module-python').then((hostname) {
      int port = int.parse(hostname.substring(hostname.indexOf(':') + 1, hostname.length));
      client.get('10.0.2.2', port, '/')
          .then((request) => request.close())
          .then((response) => response.fold([], (p, e) => p..addAll(e)))
          .then((body) {
            _sendResponse(request.response,
                          HttpStatus.NOT_FOUND,
                          'Hello from Dart module (${request.uri.path})\n'
                          '${UTF8.decode(body)}).');
      });
    });
  });
}

You should see that the Dart module calls the Python module.

The code above uses the dart:io HttpClient, but you can use the http package as well.

**Comment by sgjesse** [comment]
You are right that the URLs returned by `context.services.modules.hostname('module name')` does not work for local development. They are just localhost:XXXX which are the URLs you can use from the host to get to each docker container running the individual modules.

However the boot2docker configuration uses the address 10.0.2.2 to get back to the host. This is the address the modules uses to call the App Engine APIs exposed (which are running on the host). If you replace localhost with 10.0.2.2 you should be able to talk to another module.

If you take the modules sample in https://github.com/dart-lang/appengine_samples, and change the _requestHandler in the Dart module (in https://github.com/dart-lang/appengine_samples/tree/master/modules/module-dart/bin) like this:

```dart
void _requestHandler(HttpRequest request) {
  request.drain().then((_) {
    var client = new HttpClient();
    context.services.modules.hostname('module-python').then((hostname) {
      int port = int.parse(hostname.substring(hostname.indexOf(':') + 1, hostname.length));
      client.get('10.0.2.2', port, '/')
          .then((request) => request.close())
          .then((response) => response.fold([], (p, e) => p..addAll(e)))
          .then((body) {
            _sendResponse(request.response,
                          HttpStatus.NOT_FOUND,
                          'Hello from Dart module (${request.uri.path})\n'
                          '${UTF8.decode(body)}).');
      });
    });
  });
}
```
You should see that the Dart module calls the Python module.

The code above uses the `dart:io` `HttpClinet`, but you can use the `http` package as well.

**Comment by ntaoo** [comment]
(Originally I reported this issue on the google group)
Thanks to your support, now it's easy to write workaround code. And I don't see the problem after the deployment.

**Comment by ntaoo** [comment]
I can call a module without this trick. Looks like this issue has been fixed in the latest appengine.

**Comment by mkustermann** [comment]
The module service has been removed due to us moving to flexible environment. There is the general [AppEngine Admin API](https://cloud.google.com/appengine/docs/admin-api/), which can be used to discovering all kinds of information (including active modules/instances, traffic splitting, etc.) - see the [migration document](https://github.com/dart-lang/appengine/wiki/Migration-from-deprecated-Managed-VMs-to-Flexible-Environment) for more information.

Since the module service is no longer available, I'll go ahead an close this issue.
