### ISSUE TITLE
The memcache expiration time is ignored

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/appengine#34]
The expiration argument passed in Memcache.set and Memcache.setAll is ignored.

**Comment by kevmoo** [comment]
@sgjesse  Is this fixed with https://github.com/dart-lang/appengine/commit/3aa0d1e9b33fa43f8b8bc7115c11352ef33099a8 ?

**Comment by mkustermann** [comment]
Yes this was fixed a while ago.
