### ISSUE TITLE
Errors that happen during runAppEngine don't surface to the dev server

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/appengine#38]
If you are watching the docker logs, you can see these issue, but they are not surfaced to dev server

...it just looks like everything hangs – a very bad experience

**Comment by mkustermann** [comment]
We on the dart team do not control the user experience, the "gcloud preview app run" tool controls this (developed by the AppEngine sdk team). It is possible to see errors by running with "--verbosity=debug" (though this prints out a lot of noise as well).

The web UI admin console of the "gcloud prview app run" had some logging view, but last time I've looked it was in a state where we couldn't properly use it.

**Comment by kevmoo** [comment]
Yeah, after digging around I've noticed this. If my server just crashes and the container closes the dev_appserver will just keep running. Will hunt down a bug on the appengine side.
