### ISSUE TITLE
Use GCE log files for non request logs

### ISSUE THREAD

**Issue by enyo** [dart-lang/appengine#39]
At the moment, logs that are being done while no HTTP Request is active are discarded. It would be great if those logs would be written to the [GCE log files](https://cloud.google.com/appengine/articles/logging#cloud_logging_and_managed_vms_apps) so they are viewable in the console.

**Comment by mkustermann** [comment]
The new version of `package:appengine` we have just released is sending request-specific and background logs to the stack driver logging service. So they should be viewable now on the logging console.
