### ISSUE TITLE
Add support for the Channel API

### ISSUE THREAD

**Issue by tonyclickspace** [dart-lang/appengine#42]
Google App Engine [doesn't support Websockets directly](https://stackoverflow.com/questions/4114902/how-can-i-run-a-websocket-server-on-top-of-gae), but does support an implementation of Websockets called [Channels](https://cloud.google.com/appengine/docs/python/channel/?csw=1), at least in Python / Java / Go.

Would be a huge benefit to be able to use Websockets and GAE together in Dart.

**Comment by sgjesse** [comment]
Dart on App Engine is using Managed VMs, which have the option of forwarding ports from the VM to the container running the Dart application. This allows direct connections from the client to the application and makes WebSocket connections possible. However this has o use a different port than the main HTTP port and connect using the IP of an actual instance.

For more information on the network configuration see
https://cloud.google.com/appengine/docs/managed-vms/config and look for _Network Settings_

You can also take a look at the following thread: https://groups.google.com/a/dartlang.org/forum/#!searchin/cloud/WebSocket/cloud/_sS3IbQTh2E/QdXEqFVUaOsJ where I posted some sample code.

As Dart is running as a _custom runtime_ it does not have access to the _App Engine Service APIs_, but have to use the _publicly available REST APIs for cloud services_. See https://cloud.google.com/appengine/docs/managed-vms/ and look for _Custom Runtimes_. This basically excludes the channel API.

As Dart on Managed VMs have been around for some time we currently do not use the public APIs for the services we provide, but we will switch at some point. For _Datastore_ and _Memcache_ this should be seamless. For _User_ and _Modules_ there might be some changes.
