### ISSUE TITLE
Implement search API

### ISSUE THREAD

**Issue by llamadonica** [dart-lang/appengine#43]
See Python docs [here](https://cloud.google.com/appengine/docs/python/search/)

**Comment by sgjesse** [comment]
As Dart is running as a custom runtime it does not have access to the App Engine Service APIs, but have to use the publicly available REST APIs for cloud services. See https://cloud.google.com/appengine/docs/managed-vms/ and look for Custom Runtimes. This basically excludes the search API.

As Dart on Managed VMs have been around for some time we currently do not use the public APIs for the services we provide, but we will switch at some point. For Datastore and Memcache this should be seamless. For User and Modules there might be some changes.

**Comment by llamadonica** [comment]
Gotcha. I'll figure out another search solution for now :)
