### ISSUE TITLE
Don't print in LoggingRpcImpl when in development

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/appengine#44]
Similar to 69ecf7e181193c06f456c8dcb2ae5f30d7610f05, I'm guessing

**Comment by kevmoo** [comment]
I wonder if this could be cleanup up a lot more if the service_scope `fork` call supported overriding the `print` call using a `ZoneSpecification` – then one could ensure every print is captured.

**Comment by kevmoo** [comment]
@sgjesse @mkustermann Thoughts?

**Comment by mkustermann** [comment]
I think this should be fixed now. The implementation of the logging service will print the requests to stdout, on deployed apps they go to the logging service.
