### ISSUE TITLE
Make /_ah/start and /_ah/stop behavior overridable

### ISSUE THREAD

**Issue by victorkwan** [dart-lang/appengine#46]
Currently, it seems that `AppEngineHttpServer` automatically drains /_ah/start and /_ah/stop requests. Would it be possible to make these endpoints configurable? I'd like to use these to configure a script that runs indefinitely. Thanks!

**Comment by tahir-jamil** [comment]
any update?

**Comment by kevmoo** [comment]
We are not doing active work on this package – except for what's needed by `pub.dev`.
