### ISSUE TITLE
Flex: IP address logging returns many values.

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/appengine#55]
At the moment, the IP addresses in `x-forwarded-for` are  in one entry – and they are common separated.

This means we get values in `protoPayload.ip` of two (or more) values.

**Comment by mkustermann** [comment]
Thanks for noticing @kevmoo !

I explicitly took the first one in the header values, see [here](https://github.com/dart-lang/appengine/commit/80d491cf956212880bd51f234be04dd4b658a5ff#diff-47063a6a97958bff1cf549c2046485ceR78). I assume this is an obscurity of `dart:io`.
