### ISSUE TITLE
Flex: "zone" is always "dummy-zone"

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/appengine#57]
Likely can pull this out of the environment, right?

https://github.com/dart-lang/appengine/blob/5f0e627c85404eb4f3a52ebef33d33c89574900c/lib/src/appengine_internal.dart#L162

**Comment by mkustermann** [comment]
It's not available in the environment.

We could either not log it (probably the best thing) or try to acquire the information via metadata server.

The only reason why I included it so far is because the old log entries had it set!

**Comment by kevmoo** [comment]
curl "http://metadata.google.internal/computeMetadata/v1/instance/zone" -H "Metadata-Flavor: Google"

We already try to connect to metadata just to see if we're in prod. https://github.com/dart-lang/appengine/blob/5f0e627c85404eb4f3a52ebef33d33c89574900c/lib/src/appengine_internal.dart#L125

Might as well make this do "real" work and get the zone.
