### ISSUE TITLE
remove memcache

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/appengine#90]
This services was never properly released, we should remove support for it.

**Comment by tvolkert** [comment]
It seems like this was done?

(too bad it's not supported, since Flutter's Cocoon server would have use for it 🙂 )

**Comment by jonasfj** [comment]
Yes, this have been removed... let's close this..

@tvolkert, we use redis through [pub.dev/packages/neat_cache](https://pub.dev/packages/neat_cache) which I tweaked to ensure we have proper reconnect logic.
See [Cloud Memorystore Redis](https://cloud.google.com/memorystore/docs/redis/) for a managed solution to hosting redis, so far works great for us.
