### ISSUE TITLE
Correct docker image

### ISSUE THREAD

**Issue by ronlobo** [dart-lang/appengine#96]
Hey there,

While diving into experimenting with dart on appengine, I noticed the dart-service (repo for the dart-pad backend) is using a different docker image than recommended in the readme:

FROM google/dart:2.1.1-dev.0.0 vs FROM google/dart-runtime

Is there an overview of available images Google provides for the dart runtime and if so which is the recommended image for usage?

**Comment by jonasfj** [comment]
I think you have a list here:
https://github.com/dart-lang/dart_docker

Maybe dartpad has special needs because it wants a recent version of dart...

**Comment by ronlobo** [comment]
Thx
