### ISSUE TITLE
Getting Metadata value hangs for a long time in CI machine

### ISSUE THREAD

**Issue by enyo** [dart-lang/appengine#98]
For some reason, the `_getMetadataValue()` function in `appengine_internal.dart` takes a few minutes to make each request to `http://metadata.google.internal/computeMetadata/v1/instance/$path` in my gitlab CI runner (so in total, it takes about 5-10 minutes to complete).

It's probably not an appengine issue, but maybe one of you has an idea what's going on?

**Comment by jonasfj** [comment]
hmm, could it be retrying the request? Maybe it's best to not call it out side of appengine...

**Comment by enyo** [comment]
I figured it out: I assume that GitLab CI runners also have a DNS that can resolve to `.internal`, and that hangs for a few minutes.

The solution I found was to add `0.0.0.0        metadata.google.internal` to `/etc/hosts` to make sure the request fails immediately.
